## Importing Required Libraries for Data Cleaning And Processing

In [1]:
# Importing Pandas library for Data Manipulation
# Importing warnings to ignore the warnings
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings("ignore")
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn import metrics

## Loading the dataset using pandas
### Syntax:Dataframe_name=pd.read_file_type_name(r"file path")

In [2]:
# Importing the Airbnb dataset using pandas
airbnb=pd.read_csv(r"C:\Users\Madhu\Downloads\Airbnb Dataset\Airbnb_Data.csv")
airbnb

,id,log_price,property_type,room_type,amenities,accommodates,bathrooms,bed_type,cancellation_policy,cleaning_fee,...,latitude,longitude,name,neighbourhood,number_of_reviews,review_scores_rating,thumbnail_url,zipcode,bedrooms,beds
0,6901257,5.010635,Apartment,Entire home/apt,"{""Wireless Internet"",""Air conditioning"",Kitche...",3,1.0,Real Bed,strict,True,...,40.696524,-73.991617,Beautiful brownstone 1-bedroom,Brooklyn Heights,2,100.0,https://a0.muscache.com/im/pictures/6d7cbbf7-c...,11201,1.0,1.0
1,6304928,5.129899,Apartment,Entire home/apt,"{""Wireless Internet"",""Air conditioning"",Kitche...",7,1.0,Real Bed,strict,True,...,40.766115,-73.989040,Superb 3BR Apt Located Near Times Square,Hell's Kitchen,6,93.0,https://a0.muscache.com/im/pictures/348a55fe-4...,10019,3.0,3.0
2,7919400,4.976734,Apartment,Entire home/apt,"{TV,""Cable TV"",""Wireless Internet"",""Air condit...",5,1.0,Real Bed,moderate,True,...,40.808110,-73.943756,The Garden Oasis,Harlem,10,92.0,https://a0.muscache.com/im/pictures/6fae5362-9...,10027,1.0,3.0
3,13418779,6.620073,House,Entire home/apt,"{TV,""Cable TV"",Internet,""Wireless Internet"",Ki...",4,1.0,Real Bed,flexible,True,...,37.772004,-122.431619,Beautiful Flat in the Heart of SF!,Lower Haight,0,NaN,https://a0.muscache.com/im/pictures/72208dad-9...,94117.0,2.0,2.0
4,3808709,4.744932,Apartment,Entire home/apt,"{TV,Internet,""Wireless Internet"",""Air conditio...",2,1.0,Real Bed,moderate,True,...,38.925627,-77.034596,Great studio in midtown DC,Columbia Heights,4,40.0,NaN,20009,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74106,14549287,4.605170,Apartment,Private room,{},1,1.0,Real Bed,flexible,False,...,40.709025,-73.939405,one room bushwick,Williamsburg,0,NaN,https://a0.muscache.com/im/pictures/55162426/6...,11206.0,1.0,1.0
74107,13281809,5.043425,Apartment,Entire home/apt,"{TV,""Cable TV"",Internet,""Wireless Internet"",Ki...",4,2.0,Real Bed,moderate,True,...,33.871549,-118.396053,Spacious Hermosa 2 BR on PCH,Hermosa Beach,16,93.0,https://a0.muscache.com/im/pictures/2b86560b-a...,90254,2.0,4.0
74108,18688039,5.220356,Apartment,Entire home/apt,"{TV,Internet,""Wireless Internet"",""Air conditio...",5,1.0,Real Bed,moderate,True,...,40.706749,-73.942377,Modern 2 Bedroom Apartment in Williamsburg,Williamsburg,43,94.0,https://a0.muscache.com/im/pictures/7fbe448c-5...,11206.0,2.0,2.0
74109,17045948,5.273000,Apartment,Entire home/apt,"{TV,""Wireless Internet"",""Air conditioning"",Kit...",2,1.0,Real Bed,strict,True,...,40.738535,-74.000157,Designer's Apartment in HEART of NYC,West Village,0,NaN,https://a0.muscache.com/im/pictures/b3971b63-0...,10011,0.0,2.0
74110,3534845,4.852030,Boat,Entire home/apt,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",4,1.0,Real Bed,moderate,False,...,33.761096,-118.192409,Cozy Boat at Shoreline Village,Long Beach,205,96.0,https://a0.muscache.com/im/pictures/22968537/d...,90802,1.0,2.0

## Shape

## Returns number of rows and columns in the dataframe.

## Syntax: Dataframe_name.shape

In [3]:
# Shape-Returns the number of rows and columns in a dataframe.
airbnb.shape

(74111, 29)

## Index

## Returns the start,stop and step values of the dataset.

## Syntax:Dataframe_name.index

In [4]:
# INDEX
airbnb.index

RangeIndex(start=0, stop=74111, step=1)

## Head

## Returns the top 5 rows of a dataset.

## Syntax:Dataframe_name.head()

In [5]:
# HEAD
airbnb.head()

,id,log_price,property_type,room_type,amenities,accommodates,bathrooms,bed_type,cancellation_policy,cleaning_fee,...,latitude,longitude,name,neighbourhood,number_of_reviews,review_scores_rating,thumbnail_url,zipcode,bedrooms,beds
0,6901257,5.010635,Apartment,Entire home/apt,"{""Wireless Internet"",""Air conditioning"",Kitche...",3,1.0,Real Bed,strict,True,...,40.696524,-73.991617,Beautiful brownstone 1-bedroom,Brooklyn Heights,2,100.0,https://a0.muscache.com/im/pictures/6d7cbbf7-c...,11201,1.0,1.0
1,6304928,5.129899,Apartment,Entire home/apt,"{""Wireless Internet"",""Air conditioning"",Kitche...",7,1.0,Real Bed,strict,True,...,40.766115,-73.989040,Superb 3BR Apt Located Near Times Square,Hell's Kitchen,6,93.0,https://a0.muscache.com/im/pictures/348a55fe-4...,10019,3.0,3.0
2,7919400,4.976734,Apartment,Entire home/apt,"{TV,""Cable TV"",""Wireless Internet"",""Air condit...",5,1.0,Real Bed,moderate,True,...,40.808110,-73.943756,The Garden Oasis,Harlem,10,92.0,https://a0.muscache.com/im/pictures/6fae5362-9...,10027,1.0,3.0
3,13418779,6.620073,House,Entire home/apt,"{TV,""Cable TV"",Internet,""Wireless Internet"",Ki...",4,1.0,Real Bed,flexible,True,...,37.772004,-122.431619,Beautiful Flat in the Heart of SF!,Lower Haight,0,NaN,https://a0.muscache.com/im/pictures/72208dad-9...,94117.0,2.0,2.0
4,3808709,4.744932,Apartment,Entire home/apt,"{TV,Internet,""Wireless Internet"",""Air conditio...",2,1.0,Real Bed,moderate,True,...,38.925627,-77.034596,Great studio in midtown DC,Columbia Heights,4,40.0,NaN,20009,0.0,1.0

## Tail

## Returns the bottom 5 rows of a dataframe.

## Syntax:Dtaframe_name.tail()

In [6]:
# TAIL
airbnb.tail()

,id,log_price,property_type,room_type,amenities,accommodates,bathrooms,bed_type,cancellation_policy,cleaning_fee,...,latitude,longitude,name,neighbourhood,number_of_reviews,review_scores_rating,thumbnail_url,zipcode,bedrooms,beds
74106,14549287,4.605170,Apartment,Private room,{},1,1.0,Real Bed,flexible,False,...,40.709025,-73.939405,one room bushwick,Williamsburg,0,NaN,https://a0.muscache.com/im/pictures/55162426/6...,11206.0,1.0,1.0
74107,13281809,5.043425,Apartment,Entire home/apt,"{TV,""Cable TV"",Internet,""Wireless Internet"",Ki...",4,2.0,Real Bed,moderate,True,...,33.871549,-118.396053,Spacious Hermosa 2 BR on PCH,Hermosa Beach,16,93.0,https://a0.muscache.com/im/pictures/2b86560b-a...,90254,2.0,4.0
74108,18688039,5.220356,Apartment,Entire home/apt,"{TV,Internet,""Wireless Internet"",""Air conditio...",5,1.0,Real Bed,moderate,True,...,40.706749,-73.942377,Modern 2 Bedroom Apartment in Williamsburg,Williamsburg,43,94.0,https://a0.muscache.com/im/pictures/7fbe448c-5...,11206.0,2.0,2.0
74109,17045948,5.273000,Apartment,Entire home/apt,"{TV,""Wireless Internet"",""Air conditioning"",Kit...",2,1.0,Real Bed,strict,True,...,40.738535,-74.000157,Designer's Apartment in HEART of NYC,West Village,0,NaN,https://a0.muscache.com/im/pictures/b3971b63-0...,10011,0.0,2.0
74110,3534845,4.852030,Boat,Entire home/apt,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",4,1.0,Real Bed,moderate,False,...,33.761096,-118.192409,Cozy Boat at Shoreline Village,Long Beach,205,96.0,https://a0.muscache.com/im/pictures/22968537/d...,90802,1.0,2.0

## Columns

## Returns the names of columns in the dataframe.

## Syntax:Dataframe_name.columns

In [7]:
# COLUMNS
airbnb.columns

Index(['id', 'log_price', 'property_type', 'room_type', 'amenities',
       'accommodates', 'bathrooms', 'bed_type', 'cancellation_policy',
       'cleaning_fee', 'city', 'description', 'first_review',
       'host_has_profile_pic', 'host_identity_verified', 'host_response_rate',
       'host_since', 'instant_bookable', 'last_review', 'latitude',
       'longitude', 'name', 'neighbourhood', 'number_of_reviews',
       'review_scores_rating', 'thumbnail_url', 'zipcode', 'bedrooms', 'beds'],
      dtype='object')

# INFO
## Returns the overview/summary of a datframe
## Number of rows,Number of Columns,Datatypes of columns,column names etc...
## Syntax:dataframe.info()

In [8]:
# INFO
airbnb.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 74111 entries, 0 to 74110
Data columns (total 29 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   id                      74111 non-null  int64
 1   log_price               74111 non-null  float64
 2   property_type           74111 non-null  object
 3   room_type               74111 non-null  object
 4   amenities               74111 non-null  object
 5   accommodates            74111 non-null  int64
 6   bathrooms               73911 non-null  float64
 7   bed_type                74111 non-null  object
 8   cancellation_policy     74111 non-null  object
 9   cleaning_fee            74111 non-null  bool
 10  city                    74111 non-null  object
 11  description             74111 non-null  object
 12  first_review            58247 non-null  object
 13  host_has_profile_pic    73923 non-null  object
 14  host_identity_verified  73923 non-null  object
 15  host_response_rate      55812 non-null  object
 16  host_since              73923 non-null  object
 17  instant_bookable        74111 non-null  object
 18  last_review             58284 non-null  object
 19  latitude                74111 non-null  float64
 20  longitude               74111 non-null  float64
 21  name                    74111 non-null  object
 22  neighbourhood           67239 non-null  object
 23  number_of_reviews       74111 non-null  int64
 24  review_scores_rating    57389 non-null  float64
 25  thumbnail_url           65895 non-null  object
 26  zipcode                 73145 non-null  object
 27  bedrooms                74020 non-null  float64
 28  beds                    73980 non-null  float64
dtypes: bool(1), float64(7), int64(3), object(18)
memory usage: 15.9+ MB

## Removing the unwanted columns for data Analysis
## Syntax:Dataframe_name.drop(['col1_name',....],axis=1,inplace=True)

In [9]:
# Removing unwanted columns for data analysis
airbnb.drop(['thumbnail_url','latitude','longitude','host_has_profile_pic','host_identity_verified','zipcode'],axis=1,inplace=True)

# DESCRIBE
## Generates discriptive stats of the dataframe
## Including count,mean,standard deviation,minimum,maximum,25quartile,median or 50th quartile, 75th quartile
## Performs only on numerical data 
## Syntax:dataframe.describe()

In [10]:
# DESCRIBE
airbnb.describe()

,id,log_price,accommodates,bathrooms,number_of_reviews,review_scores_rating,bedrooms,beds
count,7.411100e+04,74111.000000,74111.000000,73911.000000,74111.000000,57389.000000,74020.000000,73980.000000
mean,1.126662e+07,4.782069,3.155146,1.235263,20.900568,94.067365,1.265793,1.710868
std,6.081735e+06,0.717394,2.153589,0.582044,37.828641,7.836556,0.852143,1.254142
min,3.440000e+02,0.000000,1.000000,0.000000,0.000000,20.000000,0.000000,0.000000
25%,6.261964e+06,4.317488,2.000000,1.000000,1.000000,92.000000,1.000000,1.000000
50%,1.225415e+07,4.709530,2.000000,1.000000,6.000000,96.000000,1.000000,1.000000
75%,1.640226e+07,5.220356,4.000000,1.000000,23.000000,100.000000,1.000000,2.000000
max,2.123090e+07,7.600402,16.000000,8.000000,605.000000,100.000000,10.000000,18.000000

# NOTE:Include object
## Syntax:dataframe.describe(include='O')
## By using this describe method we can find the high frequently occuring value.
## Becauase this if any null values in categorical data we can handle them using this method

In [11]:
# Describe
airbnb.describe(include='O')

,property_type,room_type,amenities,bed_type,cancellation_policy,city,description,first_review,host_response_rate,host_since,instant_bookable,last_review,name,neighbourhood
count,74111,74111,74111,74111,74111,74111,74111,58247,55812,73923,74111,58284,74111,67239
unique,35,3,67122,5,5,6,73479,2554,80,3087,2,1371,73359,619
top,Apartment,Entire home/apt,{},Real Bed,strict,NYC,"Hello, I've been running guest house for Korea...",2017-01-01,100%,2015-03-30,f,2017-04-30,Bunk bed in the Treat Street Clubhouse,Williamsburg
freq,49003,41310,586,72028,32374,32349,8,293,43254,246,54660,1344,8,2862

# nunique
## Returns the count of unique values in the tables or columns.
## Syntax:dataframe.nunique()

In [12]:
# nunique
airbnb.nunique()

id                      74111
log_price                 767
property_type              35
room_type                   3
amenities               67122
accommodates               16
bathrooms                  17
bed_type                    5
cancellation_policy         5
cleaning_fee                2
city                        6
description             73479
first_review             2554
host_response_rate         80
host_since               3087
instant_bookable            2
last_review              1371
name                    73359
neighbourhood             619
number_of_reviews         371
review_scores_rating       54
bedrooms                   11
beds                       18
dtype: int64

# dtypes 
## Returns the data types of columns
## Syntax:dataframe.dtypes

In [13]:
# Data Types
airbnb.dtypes

id                        int64
log_price               float64
property_type            object
room_type                object
amenities                object
accommodates              int64
bathrooms               float64
bed_type                 object
cancellation_policy      object
cleaning_fee               bool
city                     object
description              object
first_review             object
host_response_rate       object
host_since               object
instant_bookable         object
last_review              object
name                     object
neighbourhood            object
number_of_reviews         int64
review_scores_rating    float64
bedrooms                float64
beds                    float64
dtype: object

# isnull
## Returns the boolean output of the null values in a dataframe
## Syntax:dataframe.isnull()

In [14]:
# isnull
airbnb.isnull()

,id,log_price,property_type,room_type,amenities,accommodates,bathrooms,bed_type,cancellation_policy,cleaning_fee,...,host_response_rate,host_since,instant_bookable,last_review,name,neighbourhood,number_of_reviews,review_scores_rating,bedrooms,beds
0,False,False,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,True,False,False,True,False,False,False,True,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74106,False,False,False,False,False,False,False,False,False,False,...,True,False,False,True,False,False,False,True,False,False
74107,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
74108,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
74109,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,False,False,False,True,False,False
74110,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

# isnull().sum()
## Returns the sum of null values in the columns.
## Syntax:dataframe.isnull().sum()

In [15]:
# isnull().sum()
airbnb.isnull().sum()

id                          0
log_price                   0
property_type               0
room_type                   0
amenities                   0
accommodates                0
bathrooms                 200
bed_type                    0
cancellation_policy         0
cleaning_fee                0
city                        0
description                 0
first_review            15864
host_response_rate      18299
host_since                188
instant_bookable            0
last_review             15827
name                        0
neighbourhood            6872
number_of_reviews           0
review_scores_rating    16722
bedrooms                   91
beds                      131
dtype: int64

# value_counts
## Counts the number of times the each value occured in a dataframe
## Syntax:dataframe.value_counts()

In [16]:
# value count
airbnb['bathrooms'].value_counts()

bathrooms
1.0    58099
2.0     7936
1.5     3801
2.5     1567
3.0     1066
3.5      429
4.0      286
0.5      209
0.0      198
4.5      116
5.0       72
8.0       41
5.5       39
6.0       24
6.5       12
7.0       10
7.5        6
Name: count, dtype: int64

# Handling Missing Values/Null Values
## IMPUTATION METHOD
## Syntax:dataframe.fillna(value="any value",inplace=True)

In [17]:
# Filling the missing values in bathrooms column ////////////
airbnb['bathrooms'].fillna(value=airbnb['bathrooms'].mean(),inplace=True)

In [18]:
# Filling the missing values in host_response_rate column
airbnb['host_response_rate'].fillna(value='100%',inplace=True)

In [19]:
# Filling the missing values in first_review column
airbnb['first_review'].fillna(value='2017-01-01',inplace=True)

In [20]:
# Filling the missing vlues in last_review column
airbnb['last_review'].fillna(value='2017-04-30',inplace=True)

In [21]:
# Filling missing values in host_since column
airbnb['host_since'].fillna(value='2015-03-30',inplace=True)

In [26]:
# Filling missing values in neighbourhood column
airbnb['neighbourhood'].fillna(value='Williamsburg',inplace=True)

In [22]:
# Filling missing values in review_scores_rating  column
airbnb['review_scores_rating'].fillna(value=airbnb['review_scores_rating'].mean(),inplace=True)

In [23]:
# Filling missing values in bedrooms column
airbnb['bedrooms'].fillna(value=airbnb['bedrooms'].max(),inplace=True)

In [24]:
# Filling the missing values in beds column
airbnb['beds'].fillna(value=airbnb['beds'].max(),inplace=True)

## Checking for null values again

In [27]:
# isnull().sum()
airbnb.isnull().sum()

id                      0
log_price               0
property_type           0
room_type               0
amenities               0
accommodates            0
bathrooms               0
bed_type                0
cancellation_policy     0
cleaning_fee            0
city                    0
description             0
first_review            0
host_response_rate      0
host_since              0
instant_bookable        0
last_review             0
name                    0
neighbourhood           0
number_of_reviews       0
review_scores_rating    0
bedrooms                0
beds                    0
dtype: int64

In [28]:
# Checking for the data types of columns
airbnb.dtypes

id                        int64
log_price               float64
property_type            object
room_type                object
amenities                object
accommodates              int64
bathrooms               float64
bed_type                 object
cancellation_policy      object
cleaning_fee               bool
city                     object
description              object
first_review             object
host_response_rate       object
host_since               object
instant_bookable         object
last_review              object
name                     object
neighbourhood            object
number_of_reviews         int64
review_scores_rating    float64
bedrooms                float64
beds                    float64
dtype: object

In [29]:
# Converting the float data type of columns bathrooms,bedrooms and beds to int
columns=['bathrooms','bedrooms','beds']

airbnb[columns]=airbnb[columns].astype(int)

In [30]:
# Convertig the object data type of columns host_since,first_review and last_review to date
attributes=['host_since','first_review','last_review']
airbnb[attributes]=airbnb[attributes].apply(pd.to_datetime)

## Duplicate values/records
## drop_duplicates
## It is used to drop the duplicate records in the dataframe
## syntax:dataframe.dropduplicates()
## Note:If the complete row records matches with the other row then it is called as duplicate row this values/records only deleted.

In [31]:
# Dropping duplicates
airbnb.drop_duplicates()

,id,log_price,property_type,room_type,amenities,accommodates,bathrooms,bed_type,cancellation_policy,cleaning_fee,...,host_response_rate,host_since,instant_bookable,last_review,name,neighbourhood,number_of_reviews,review_scores_rating,bedrooms,beds
0,6901257,5.010635,Apartment,Entire home/apt,"{""Wireless Internet"",""Air conditioning"",Kitche...",3,1,Real Bed,strict,True,...,100%,2012-03-26,f,2016-07-18,Beautiful brownstone 1-bedroom,Brooklyn Heights,2,100.000000,1,1
1,6304928,5.129899,Apartment,Entire home/apt,"{""Wireless Internet"",""Air conditioning"",Kitche...",7,1,Real Bed,strict,True,...,100%,2017-06-19,t,2017-09-23,Superb 3BR Apt Located Near Times Square,Hell's Kitchen,6,93.000000,3,3
2,7919400,4.976734,Apartment,Entire home/apt,"{TV,""Cable TV"",""Wireless Internet"",""Air condit...",5,1,Real Bed,moderate,True,...,100%,2016-10-25,t,2017-09-14,The Garden Oasis,Harlem,10,92.000000,1,3
3,13418779,6.620073,House,Entire home/apt,"{TV,""Cable TV"",Internet,""Wireless Internet"",Ki...",4,1,Real Bed,flexible,True,...,100%,2015-04-19,f,2017-04-30,Beautiful Flat in the Heart of SF!,Lower Haight,0,94.067365,2,2
4,3808709,4.744932,Apartment,Entire home/apt,"{TV,Internet,""Wireless Internet"",""Air conditio...",2,1,Real Bed,moderate,True,...,100%,2015-03-01,t,2017-01-22,Great studio in midtown DC,Columbia Heights,4,40.000000,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74106,14549287,4.605170,Apartment,Private room,{},1,1,Real Bed,flexible,False,...,100%,2013-03-24,f,2017-04-30,one room bushwick,Williamsburg,0,94.067365,1,1
74107,13281809,5.043425,Apartment,Entire home/apt,"{TV,""Cable TV"",Internet,""Wireless Internet"",Ki...",4,2,Real Bed,moderate,True,...,100%,2016-05-03,f,2017-04-15,Spacious Hermosa 2 BR on PCH,Hermosa Beach,16,93.000000,2,4
74108,18688039,5.220356,Apartment,Entire home/apt,"{TV,Internet,""Wireless Internet"",""Air conditio...",5,1,Real Bed,moderate,True,...,100%,2012-01-05,t,2017-09-10,Modern 2 Bedroom Apartment in Williamsburg,Williamsburg,43,94.000000,2,2
74109,17045948,5.273000,Apartment,Entire home/apt,"{TV,""Wireless Internet"",""Air conditioning"",Kit...",2,1,Real Bed,strict,True,...,100%,2017-09-17,t,2017-04-30,Designer's Apartment in HEART of NYC,West Village,0,94.067365,0,2
74110,3534845,4.852030,Boat,Entire home/apt,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",4,1,Real Bed,moderate,False,...,100%,2012-11-26,f,2017-04-30,Cozy Boat at Shoreline Village,Long Beach,205,96.000000,1,2

## Note:We can see no duplicate records in the datframe

## Average of log Prices by Cities

In [32]:
city=airbnb.groupby('city')['log_price'].mean().sort_values(ascending=False)
city

city
SF         5.170014
DC         4.986798
Boston     4.884035
LA         4.720496
NYC        4.719340
Chicago    4.620079
Name: log_price, dtype: float64

## Average of log prices by Property Type

In [33]:
# Average prices by property type
property_type=airbnb.groupby('property_type')['log_price'].mean().sort_values(ascending=False)
property_type

property_type
Timeshare             5.602600
Lighthouse            5.521461
Vacation home         5.420951
Castle                5.368424
Earth House           5.285391
Tipi                  5.246118
Train                 5.204399
Boat                  5.200865
Serviced apartment    5.147467
Villa                 5.112427
Boutique hotel        5.083352
Condominium           5.026539
Island                5.010635
Loft                  5.007919
Other                 4.946367
Yurt                  4.944360
Cave                  4.909373
Treehouse             4.845520
Townhouse             4.833539
In-law                4.816649
House                 4.797114
Bungalow              4.783268
Chalet                4.764325
Apartment             4.758850
Guest suite           4.717513
Guesthouse            4.685184
Cabin                 4.646499
Parking Space         4.605170
Camper/RV             4.602238
Bed & Breakfast       4.556068
Casa particular       4.382027
Tent                  4.197131
Hut                   4.022837
Dorm                  3.746140
Hostel                3.647333
Name: log_price, dtype: float64

## Month wise Average log prices

In [84]:
# Month wise average log prices
airbnb['Month_name']=airbnb['host_since'].dt.strftime('%B')
Month=airbnb.groupby('Month_name')['log_price'].mean().sort_values(ascending=False)
Month

Month_name
January      4.807571
September    4.806097
November     4.799974
October      4.788549
February     4.788045
March        4.783974
August       4.778646
June         4.776660
July         4.774827
May          4.766789
April        4.760172
December     4.759882
Name: log_price, dtype: float64

## Log Price:
## Instead of recording the actual price (e.g., $100, $300), they store log(price).

## This transformation shrinks large prices and spreads out small prices, making the data more normal (less skewed).

## It helps in statistical modeling (like linear regression) because many models assume the target variable is normally distributed.

In [34]:
# Converting log price to actual price
airbnb['actual_price']=np.exp(airbnb['log_price'])
airbnb['actual_price']

0        150.0
1        169.0
2        145.0
3        750.0
4        115.0
         ...
74106    100.0
74107    155.0
74108    185.0
74109    195.0
74110    128.0
Name: actual_price, Length: 74111, dtype: float64

## Actual Pricing analysis

In [35]:
# Average Actual pricing by city
actual_price_city=airbnb.groupby('city')['actual_price'].mean().sort_values(ascending=False)
actual_price_city

city
SF         227.372552
DC         217.933368
Boston     165.631488
LA         155.388233
NYC        143.024576
Chicago    132.476472
Name: actual_price, dtype: float64

## The city SF has high prices for rooms in airbnb

In [36]:
# Average of Actual price by property type
property_type_actual=airbnb.groupby('property_type')['actual_price'].mean().sort_values(ascending=False)
property_type_actual

property_type
Villa                 383.687151
Earth House           356.250000
Timeshare             310.454545
Treehouse             279.142857
Vacation home         277.000000
Castle                256.076923
Boat                  252.246154
Lighthouse            250.000000
Tipi                  232.333333
Serviced apartment    224.142857
Boutique hotel        221.623188
Other                 212.448105
Condominium           204.647856
Loft                  203.913183
House                 188.305857
Train                 182.500000
Townhouse             182.355792
Yurt                  163.444444
Island                150.000000
Apartment             146.368467
Cave                  136.000000
In-law                135.929577
Bungalow              135.387978
Camper/RV             132.627660
Guest suite           129.447154
Chalet                127.833333
Guesthouse            125.257028
Cabin                 118.125000
Bed & Breakfast       116.586580
Parking Space         100.000000
Tent                   83.666667
Casa particular        80.000000
Hut                    63.625000
Hostel                 57.000000
Dorm                   51.253521
Name: actual_price, dtype: float64

## Villa property type has the highest average

In [95]:
# Average of actual price by month
airbnb['Month_name']=airbnb['host_since'].dt.strftime('%B')
Month_actual=airbnb.groupby('Month_name')['actual_price'].mean().sort_values(ascending=False)
Month_actual

Month_name
January      171.613136
September    163.636228
November     161.859706
October      160.945364
February     160.034884
August       160.016424
March        159.370772
December     159.102505
July         158.715772
June         158.074095
April        157.277166
May          155.758782
Name: actual_price, dtype: float64

## January month has the highest average actual price

## Airbnb actual pricing based on seasons

In [37]:
# Creating the month column
airbnb['month']=airbnb['last_review'].dt.month
# Defining the months
def get_season(month):
    if month in [12, 1, 2]:
        return 'Winter'
    elif month in [3, 4, 5]:
        return 'Spring'
    elif month in [6, 7, 8]:
        return 'Summer'
    else:
        return 'Fall'
airbnb['season'] = airbnb['month'].apply(get_season)
# Group by season
seasonal_price = airbnb.groupby('season')['actual_price'].mean().sort_values(ascending=False)

print(seasonal_price)

season
Spring    169.139201
Winter    157.993787
Summer    156.415821
Fall      148.589427
Name: actual_price, dtype: float64

## Spring season has highest average actual price

## Exporting the cleaned data to the file
## Syntax:dataframe_name.to_file_name_type('file path',index=false)

In [38]:
# Exporting the cleaned data into the csv file
airbnb.to_csv(r"C:\Users\Madhu\Documents\Internship Data Sets\Airbnb Cleaned Data.csv",index=False)

## Logistic Regression : Predict the pricing of rooms.

In [102]:
# Selecting the columns that helps to predict the price
X=airbnb[['city','property_type','accommodates','beds','review_scores_rating','month']]
X=pd.get_dummies(X,drop_first=True)
# Defining Target variable
y=airbnb['actual_price']

## Machine learning models cannot understand text (like "Apartment" or "House").

## get_dummies() converts text columns into 0s and 1s (one-hot encoding).

## drop_first=True prevents multicollinearity (keeps one less dummy column to avoid redundancy).

In [103]:
# Splitting the data into training and testing
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

## Training set (X_train, y_train): 80% of data to train the model.

## Testing set (X_test, y_test): 20% of data to test the model (check how well it learned).

## random_state=42: Sets a fixed random seed so that you always get the same split every time you run it.

In [106]:
## Initialising the train model
model=LinearRegression()
model.fit(X_train,y_train)

LinearRegression()

## model = LinearRegression(): Create an empty linear regression model.

## fit(X_train, y_train): Find the best line (equation) that fits the training data by minimizing the error.

In [114]:
# Making the predictions
y_pred=model.predict(X_test)
print(y_pred)

[ 76.01215567  77.99260125 218.19704618 ... 118.19348185 417.41778252
  83.28321764]

## Use the trained model to predict prices for the unseen testing data (X_test).

## y_pred now contains predicted prices.

In [112]:
# Evaluating the model
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error
print('R2 Score:', r2_score(y_test, y_pred))
print('RMSE:', np.sqrt(mean_squared_error(y_test, y_pred)))

R2 Score: 0.2959811742161558
RMSE: 143.5890582584538

## R2 Score: Measures how much variation in price the model can explain.

### Range: 0 to 1.

### Closer to 1 means better fit.

## RMSE (Root Mean Squared Error):

### Measures the average error in your predictions.

### Lower RMSE means more accurate predictions.